### ISSUE TITLE
I can't play the MP_Subway map in funbot 2.7.1

### ISSUE THREAD

**Issue by SunFlowerXiXi** [Joe91/fun-bots#286]
### Scope

Core

### What happened?

I found in version fun-bot 2.7.1 that the server program would crash if I changed the map to MP_Subway，I have tested that this problem also occurs when only funbot plug-ins are loaded. At present, I only test ConquestLarge and RushLarge modes.

### What was expected?

I hope that this problem can be fixed in the future version. Thank you very much

### How can we reproduce and test it?

Use the funbot 2.7.1 release and replace the map with MP_ Subway ConquestLarge0 1 MP_ The Subway RushLarge0 1 server will crash.

### Version of fun-bots and VU?

The funbot version I use is the 2.7.1 release, and the VU version is 19968

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Sorry for the late reply:
The name you are using is wrong: "MP_ The Subway RushLarge0 1" does not exist.
Have you tried to use the real names from the maplist.txt?
`MP_Subway RushLarge0 1`

**Comment by SunFlowerXiXi** [comment]
> 
Sorry, because my English is not very good, I use Google Translate to communicate with you. "The" may be added by the translation software. After my test, I found that the RushLarge0 and ConquestLarge0 crashes of MP_Subway were caused by USE_LOAD_BUNDLE_BUGFIX = true in the Registry.lua configuration file. After changing it to USE_LOAD_BUNDLE_BUGFIX = false, this problem was solved. But setting USE_LOAD_BUNDLE_BUGFIX to false will increase the probability of no weapons after resurrection. In 2.7.0RC version, USE_LOAD_BUNDLE_BUGFIX can be set to true and play games, I hope you can solve this problem. Thank you again for your hard work!

**Comment by Joe91** [comment]
This is really intersting. Will have a look at this. Too many options to play around with this mod :-)

**Comment by Joe91** [comment]
Can't reproduce this on the dev-branch. Can you try if this still happens on the dev-branch for you?

**Comment by Joe91** [comment]
That is really stange! But I can't find anything strange that would cause this... @lywit do you have any idea what could cause such strange behaviour? Is the bundle of MP_11 conflicting with MP_Subway in some strange way?
For me it also happens on V2.7.0-RC1 and earlier...

**Comment by MiniGui98** [comment]
Hi, 

I can confirm this issue is still happening. Setting "USE_LOAD_BUNDLE_BUGFIX" to true in the registry fixes the missing weapon bug but it also makes MP_Subway crash. Setting it to false fixes the issue but as SunFlower stated, this makes the missing weapon bug happening again.

Are there any news about this?

Thank you very much, awesome mod by the way :-)

**Comment by lywit** [comment]
It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.

Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.

@Joe91 it may be possible to build some sort of 'bundle compatibility mapping' where certain bundles get loaded for certain maps.

**Comment by MiniGui98** [comment]
> It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.
> 
> Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.

I have no idea how/why loading another map fixes the missing weapon bug (and why having shared asset with it crashes the server lol), but would loading another map through the shared ini lua also fix the issue? For example, say MP_003 (Teheran Highway) or an expansion map? 

I guess I could live with having one "banned" map in my list if it's to play Metro with the fix enabled. Would it work or does it *have* to be MP_011 specifically mounted for the fix to work?

**Comment by Joe91** [comment]
> It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.
> 
> Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.
> 
> @Joe91 it may be possible to build some sort of 'bundle compatibility mapping' where certain bundles get loaded for certain maps.

Yeah of course, that would be possible... Do you have another bundle guid you would recommend? I can try to code this during the next week...

**Comment by Joe91** [comment]
> > It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.
> > 
> > Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.
> 
> I have no idea how/why loading another map fixes the missing weapon bug (and why having shared asset with it crashes the server lol), but would loading another map through the shared ini lua also fix the issue? For example, say MP_003 (Teheran Highway) or an expansion map? 
> 
> I guess I could live with having one "banned" map in my list if it's to play Metro with the fix enabled. Would it work or does it *have* to be MP_011 specifically mounted for the fix to work?

In a quick fix I can try to not load the bundle if the map is metro (then at least it should not crash anymore). But the idea from @lywit  sounds really interesting!

**Comment by lywit** [comment]
> > It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.
> > Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.
> > @Joe91 it may be possible to build some sort of 'bundle compatibility mapping' where certain bundles get loaded for certain maps.
> 
> Yeah of course, that would be possible... Do you have another bundle guid you would recommend? I can try to code this during the next week...

It would require some testing, but I'd recommend trying the 'simplest' maps that have the fewest amount of assets.
Maybe Noshahr Canals MP_017 would work as it doesn't contain many assets.



> > > It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.
> > > Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.
> > 
> > 
> > I have no idea how/why loading another map fixes the missing weapon bug (and why having shared asset with it crashes the server lol), but would loading another map through the shared ini lua also fix the issue? For example, say MP_003 (Teheran Highway) or an expansion map?
> > I guess I could live with having one "banned" map in my list if it's to play Metro with the fix enabled. Would it work or does it _have_ to be MP_011 specifically mounted for the fix to work?
> 
> In a quick fix I can try to not load the bundle if the map is metro (then at least it should not crash anymore). But the idea from @lywit sounds really interesting!

That would work for now!
This logic could easily be expanded to load a different bundle if the map is Metro.



> > It may help to swap the the bundle that's being loaded in the shared init lua code for a different TDM gamemode one.
> > Currently by using the bundle fix we're loading Seine Crossing TDM, this bundle shares a lot of assets with Operation Metro, which I suspect is what's causing the issue.
> 
> I have no idea how/why loading another map fixes the missing weapon bug (and why having shared asset with it crashes the server lol), but would loading another map through the shared ini lua also fix the issue? For example, say MP_003 (Teheran Highway) or an expansion map?
> 
> I guess I could live with having one "banned" map in my list if it's to play Metro with the fix enabled. Would it work or does it _have_ to be MP_011 specifically mounted for the fix to work?

It can be any map that supports Team Deathmatch :)
You'll have to go into ```fun-bots/ext/Shared/__init__.lua``` and change 3 events.
The following is untested, but this is what you'd change to load MP_03:

```lua
function FunBotShared:OnResourceManagerLoadBundle(p_HookCtx, p_Bundles, p_Compartment)
	if #p_Bundles == 1 and p_Bundles[1] == SharedUtils:GetLevelName() then
		m_Logger:Write('Injecting bundles...')
		p_Bundles = {
			'Levels/MP_003/MP_003',
			p_Bundles[1],
		}
		p_HookCtx:Pass(p_Bundles, p_Compartment)
	end
end

-- Function for Weapon Disappear Workaround.
function FunBotShared:OnLevelLoadResources()
	m_Logger:Write('Mounting superbundle...')
	ResourceManager:MountSuperBundle('Levels/MP_003/MP_003') -- Mount Superbundles.
end

function FunBotShared:OnLevelRegisterEntityResources(p_LevelData)
	m_Logger:Write('Registering instances...')
	local s_aRegistry = RegistryContainer(ResourceManager:SearchForInstanceByGuid(Guid('0B40AC87-7AFF-EDDE-949A-FCBF42CF7126'))) -- Assets from: Levels/MP_003/MP_003
	ResourceManager:AddRegistry(s_aRegistry, ResourceCompartment.ResourceCompartment_Game)
end
```

**Comment by Joe91** [comment]
Hi, I just added the code from @lywit in a new commit and it at least doesn't crash anymore. Can you try if this fixes your issue?
